[build]
  publish = "."
  functions = "netlify/functions"
  command = "echo 'Sitio estático, no requiere build'"

[functions]
  node_bundler = "esbuild"

# Evita publicar carpetas que no son parte del sitio
[build.processing]
  skip_processing = false
